all:
	gcc -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL mainwindow.c libs/raylib/libraylib.a -o a.out

#all:
#	gcc mainwindow.c libs/raylib/libraylib.a -o a.out -lraylib -lm -ldl -lpthread

#test:
#	gcc opengl_example.c libs/raylib/libraylib.a -o a.out -lraylib -lm -ldl -lpthread
